export const SELLER_CREATE_PRODUCT_REQUEST = 'SELLER_CREATE_PRODUCT_REQUEST';
export const SELLER_CREATE_PRODUCT_SUCCESS = 'SELLER_CREATE_PRODUCT_SUCCESS';
export const SELLER_CREATE_PRODUCT_FAIL = 'SELLER_CREATE_PRODUCT_FAIL';